package server;

public enum Response{
    SERVER_STOPPED_LISTENING,
    SERVER_STARTED_LISTENING,
    SERVER_CLOSED,
    CLIENT_DISCONNECT,
    WRITER,
    INVALID_WRITER,
    GET_ARTICLE,
    GET_ALL_ARTICLES,
    CREATE_ARTICLE,
    DELETE_ARTICLE,
    SERVER_INFO,
    REFRESH

}
