package client;

public enum Response {

    SERVER_CLOSED,
    SERVER_STOPPED_LISTENING,
    SERVER_STARTED_LISTENING,
    WRITER,
    INVALID_WRITER,
    CLIENT_DISCONNECT,
    GET_ARTICLE,
    GET_ALL_ARTICLES,
    DELETE_ARTICLE,
    CREATE_ARTICLE,
    SERVER_INFO,
    GET_WRITER,
    REFRESH

}
